{
 "title": "PrAddict",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"arduino_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"arduino_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Heart\")\n  |> filter(fn: (r) => r[\"_field\"] == \"values\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "m/s^2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"arduino_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Acceleration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"values\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}